CREATE TABLE IF NOT EXISTS wallets (
    id    VARCHAR(36) UNIQUE                                        NOT NULL,
    balance  BIGINT                                                 NOT NULL
);

CREATE TABLE IF NOT EXISTS operations (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY       NOT NULL,
    wallet_id VARCHAR(36)                                           NOT NULL,
    type  VARCHAR(8)                                                NOT NULL,
    amount BIGINT                                                   NOT NULL,
    created TIMESTAMP                                               NOT NULL,
    CONSTRAINT wallets_operations_fk FOREIGN KEY (wallet_id) REFERENCES wallets (id)
);