CREATE TABLE IF NOT EXISTS wallet (
    id    VARCHAR(36) PRIMARY KEY                                   NOT NULL,
    balance  BIGINT                                                 NOT NULL
);

CREATE TABLE IF NOT EXISTS operation (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY       NOT NULL,
    wallet_id VARCHAR(36)                                           NOT NULL,
    type  VARCHAR(8)                                                NOT NULL,
    amount BIGINT                                                   NOT NULL,
    created TIMESTAMP                                               NOT NULL,
    CONSTRAINT wallet_operation_fk FOREIGN KEY (wallet_id) REFERENCES wallet (id)
);